sudo: true

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

script:
  - cd testing && mkdir roles && cd roles
  - ln -s ../../../ansible-git ansible-git && cd ..
  - ansible-playbook -i hosts play_git.yml
